<script lang="ts">
  import art from "./solarpunk.svg";

  // generated by scripts/solarpunk-house.js
  const layout = {
    width: 340,
    height: 304,
    sky: "left:5.882cqw;top:0cqw;width:88.235cqw",
    clouds: [
      {
        style:
          "top:5.882cqw;width:12.706cqw;translate:26.471cqw 0;animation-duration:95s;animation-delay:-30s"
      },
      {
        style:
          "top:12.941cqw;width:8.753cqw;translate:51.471cqw 0;animation-duration:130s;animation-delay:-95s"
      }
    ],
    twinkles: [
      { style: "left:32.353cqw;top:11.765cqw;animation-delay:-0s" },
      { style: "left:55.882cqw;top:5.294cqw;animation-delay:-0.9s" },
      { style: "left:11.765cqw;top:30cqw;animation-delay:-1.8s" },
      { style: "left:47.059cqw;top:17.647cqw;animation-delay:-2.7s" },
      { style: "left:6.471cqw;top:17.647cqw;animation-delay:-3.6s" }
    ],
    rotor: "left:67.517cqw;top:18.702cqw;transform:matrix(0.94,0.139,0,0.914,0,0)",
    blades: {
      viewBox: "-36 -36 72 72",
      style: "width:21.176cqw;margin:-10.588cqw 0 0 -10.588cqw",
      path: "M-1.3 -2.5C-2.6 -12 -1.7 -26 -0.4 -35.4Q0 -36 0.5 -35.3C1.5 -28 2.6 -14 1.5 -2.5Z"
    },
    beacon: "left:69.87cqw;top:15.131cqw",
    fall: "left:33.397cqw;top:70.333cqw;width:2.059cqw;height:10.294cqw",
    fireflies: [
      { style: "left:28.235cqw;top:62.353cqw;animation-delay:-0s,-0s" },
      { style: "left:40cqw;top:67.647cqw;animation-delay:-0.83s,-0.47s" },
      { style: "left:61.765cqw;top:62.941cqw;animation-delay:-1.66s,-0.94s" },
      { style: "left:68.824cqw;top:70.588cqw;animation-delay:-2.49s,-1.41s" },
      { style: "left:21.176cqw;top:67.647cqw;animation-delay:-3.32s,-1.88s" },
      { style: "left:52.941cqw;top:75.294cqw;animation-delay:-4.15s,-2.35s" },
      { style: "left:77.059cqw;top:66.471cqw;animation-delay:-4.98s,-2.82s" }
    ],
    bees: [
      { style: "left:27.483cqw;top:59.994cqw;animation-delay:-0s" },
      { style: "left:28.366cqw;top:59.405cqw;animation-delay:-1.3s" },
      { style: "left:29.248cqw;top:58.817cqw;animation-delay:-2.6s" }
    ]
  };
  // end generated
</script>

<!--
  The drawing is a fixed 3/4 view of a 3D model, flattened to SVG by scripts/solarpunk-house.js:
  a single file cached like any other image, whose night palette is picked by the #night fragment. Only the small layers on top of it move, and
  they animate nothing but transform and opacity, so the browser never repaints the drawing.
-->
<div
  class="scene"
  style:aspect-ratio="{layout.width} / {layout.height}"
  role="img"
  aria-label="Illustration of a solarpunk house on a floating island: a rammed-earth cottage with solar panels on its roof, a glass dome greenhouse, a wind turbine, fruit trees and cypresses, raised vegetable beds, a beehive and a pond that spills over the edge as a waterfall"
>
  <img
    class="art art-day"
    src={art}
    alt=""
    width={layout.width}
    height={layout.height}
    decoding="async"
  />
  <img
    class="art art-night"
    src="{art}#night"
    alt=""
    width={layout.width}
    height={layout.height}
    decoding="async"
  />

  <div class="sky" style={layout.sky}>
    <div class="by-day">
      {#each layout.clouds as cloud, i (i)}
        <svg class="cloud" viewBox="-1 0 50 18" style={cloud.style}>
          <path d="M9 18a9 9 0 0 1-1-17.9A11 11 0 0 1 28 3a8 8 0 0 1 12 5a5 5 0 0 1 0 10Z" />
        </svg>
      {/each}
    </div>
    <div class="by-night">
      {#each layout.twinkles as star, i (i)}
        <span class="twinkle" style={star.style}></span>
      {/each}
      <span class="shooting"></span>
    </div>
  </div>

  <div class="rotor" style={layout.rotor}>
    <svg class="blades" viewBox={layout.blades.viewBox} style={layout.blades.style}>
      {#each [0, 120, 240] as angle (angle)}
        <path transform="rotate({angle})" d={layout.blades.path} />
      {/each}
      <circle class="hub" r="3" />
      <circle r="2" />
    </svg>
  </div>

  <span class="fall" style={layout.fall}><span></span></span>

  <div class="by-day">
    {#each layout.bees as bee, i (i)}
      <span class="bee" style={bee.style}></span>
    {/each}
  </div>
  <div class="by-night">
    <span class="beacon" style={layout.beacon}></span>
    {#each layout.fireflies as firefly, i (i)}
      <span class="firefly" style={firefly.style}></span>
    {/each}
  </div>
</div>

<style>
  /* Colours of the moving parts; the drawing's own palette is in scripts/solarpunk-house.js */
  .scene {
    --cloud: #fdfaf5;
    --star: #fffaf0;
    --metal: #f6f3ed;
    --metal-deep: #d2cbc0;
    --water-lit: #e3ece9;
    --glow: #ffcf8f;
    --beacon: #ff6a4d;
    --bee: #4b4540;
    --bee-stripe: #dcb673;

    position: relative;
    container-type: inline-size;
  }

  :global(.dark) .scene {
    --metal: #aaa69f;
    --metal-deep: #7d7972;
    --water-lit: #69798a;
    --glow: #ffc684;
  }

  .art,
  .by-day,
  .by-night {
    position: absolute;
    inset: 0;
    width: 100%;
    height: 100%;
  }

  /* Day and night cross-fade. Both are the same file, so the switch never waits on the network */
  .art {
    transition: opacity 0.6s;
  }

  .art-night,
  :global(.dark) .scene .art-day {
    opacity: 0;
  }

  :global(.dark) .scene .art-night {
    opacity: 1;
  }

  /* Animated layers are removed rather than hidden, so nothing animates out of sight */
  .by-night,
  :global(.dark) .scene .by-day {
    display: none;
  }

  :global(.dark) .scene .by-night {
    display: block;
  }

  .sky,
  .rotor,
  .cloud,
  .twinkle,
  .shooting,
  .fall,
  .bee,
  .beacon,
  .firefly {
    position: absolute;
  }

  .sky {
    aspect-ratio: 1;
    overflow: hidden;
    border-radius: 50%;
  }

  .cloud {
    left: 0;
    fill: var(--cloud);
    opacity: 0.9;
    animation: drift linear infinite;
  }

  .twinkle {
    width: 0.4cqw;
    height: 0.4cqw;
    border-radius: 50%;
    background: var(--star);
    animation: twinkle 4.5s ease-in-out infinite;
  }

  .shooting {
    top: 18%;
    left: 62%;
    width: 9cqw;
    height: 1px;
    opacity: 0;
    rotate: -28deg;
    background: linear-gradient(90deg, var(--star), transparent);
    animation: shoot 11s ease-in 4s infinite;
  }

  .rotor {
    width: 0;
    height: 0;
  }

  .blades {
    display: block;
    fill: var(--metal);
    animation: spin 7s linear infinite;
  }

  .hub {
    fill: var(--metal-deep);
  }

  .fall {
    overflow: hidden;
    mask-image: linear-gradient(#000 40%, transparent);
  }

  .fall span {
    position: absolute;
    inset: -100% 0 0;
    background: repeating-linear-gradient(
      transparent 0,
      color-mix(in oklab, var(--water-lit) 55%, transparent) 0.6cqw,
      transparent 1.4cqw 2.2cqw
    );
    animation: flow 1.4s linear infinite;
  }

  .bee {
    width: 0.7cqw;
    height: 0.55cqw;
    border-radius: 50%;
    background: var(--bee);
    box-shadow: inset 0.25cqw 0 var(--bee-stripe);
    animation: buzz 3.2s ease-in-out infinite;
  }

  .beacon {
    width: 0.8cqw;
    height: 0.8cqw;
    margin: -0.4cqw 0 0 -0.4cqw;
    border-radius: 50%;
    background: var(--beacon);
    box-shadow: 0 0 1.2cqw 0.3cqw color-mix(in oklab, var(--beacon) 60%, transparent);
    animation: beacon 2.4s steps(1) infinite;
  }

  .firefly {
    width: 0.9cqw;
    height: 0.9cqw;
    border-radius: 50%;
    background: var(--glow);
    box-shadow: 0 0 1.8cqw 0.5cqw color-mix(in oklab, var(--glow) 70%, transparent);
    animation:
      wander 7s ease-in-out infinite alternate,
      blink 2.6s ease-in-out infinite;
  }

  @keyframes drift {
    from {
      translate: -20cqw 0;
    }
    to {
      translate: 90cqw 0;
    }
  }

  @keyframes twinkle {
    0%,
    100% {
      opacity: 0.2;
    }
    50% {
      opacity: 1;
    }
  }

  @keyframes shoot {
    0%,
    92% {
      opacity: 0;
      translate: 0 0;
    }
    94% {
      opacity: 1;
    }
    100% {
      opacity: 0;
      translate: -18cqw 9cqw;
    }
  }

  @keyframes spin {
    to {
      rotate: 360deg;
    }
  }

  @keyframes flow {
    to {
      translate: 0 50%;
    }
  }

  @keyframes buzz {
    0%,
    100% {
      translate: 0 0;
    }
    25% {
      translate: 2.2cqw -1.4cqw;
    }
    50% {
      translate: 0.6cqw -2.6cqw;
    }
    75% {
      translate: -1.8cqw -1cqw;
    }
  }

  @keyframes beacon {
    0%,
    60% {
      opacity: 0.25;
    }
    70% {
      opacity: 1;
    }
  }

  @keyframes wander {
    to {
      translate: 2.4cqw -3cqw;
    }
  }

  @keyframes blink {
    0%,
    100% {
      opacity: 0.15;
    }
    50% {
      opacity: 1;
    }
  }
</style>
